# Players Exploration

Objective: load clubs and players data, and identify which players
belong to clubs from the Brazilian Série A (competition_id = BRA1).

In [1]:
import pandas as pd

## Loading clubs data

In [2]:
df_clubs = pd.read_csv('../data/raw/clubs.csv')

## Exploring clubs structure

In [3]:
df_clubs.head()

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,10,arminia-bielefeld,Arminia Bielefeld,L1,NaN,27,25.3,15,55.6,4,SchücoArena,26515,+€5.90m,NaN,2021,../data/raw/transfermarkt-scraper/2021/clubs.j...,https://www.transfermarkt.co.uk/arminia-bielef...
1,10004,paris-fc,Paris FC,FR1,NaN,27,27.2,14,51.9,7,Stade Jean Bouin,19904,€-25.00m,Stéphane Gilli,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/paris-fc/start...
2,10010,esporte-clube-bahia,Esporte Clube Bahia,BRA1,NaN,32,26.6,9,28.1,3,Arena Fonte Nova,47364,+€8.14m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
3,1003,leicester-city,Leicester City,GB1,NaN,29,25.9,17,58.6,9,King Power Stadium,32259,+€57.30m,Steve Cooper,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/leicester-city...
4,1005,us-lecce,US Lecce,IT1,NaN,39,23.8,36,92.3,10,Ettore Giardiniero,31559,+€3.35m,Eusebio Di Francesco,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-lecce/start...

In [4]:
df_clubs.info()

<class 'pandas.DataFrame'>
RangeIndex: 796 entries, 0 to 795
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   club_id                  796 non-null    int64
 1   club_code                796 non-null    str
 2   name                     796 non-null    str
 3   domestic_competition_id  796 non-null    str
 4   total_market_value       0 non-null      float64
 5   squad_size               796 non-null    int64
 6   average_age              758 non-null    float64
 7   foreigners_number        796 non-null    int64
 8   foreigners_percentage    736 non-null    float64
 9   national_team_players    796 non-null    int64
 10  stadium_name             796 non-null    str
 11  stadium_seats            796 non-null    int64
 12  net_transfer_record      796 non-null    str
 13  coach_name               403 non-null    str
 14  last_season              796 non-null    int64
 15  filename                 796 non-null    str
 16  url                      796 non-null    str
dtypes: float64(3), int64(6), str(8)
memory usage: 105.8 KB

## Filtering Brazilian clubs

In [5]:
df_clubs_brazil = df_clubs[df_clubs['domestic_competition_id'] == 'BRA1']
df_clubs_brazil

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
2,10010,esporte-clube-bahia,Esporte Clube Bahia,BRA1,NaN,32,26.6,9,28.1,3,Arena Fonte Nova,47364,+€8.14m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
11,1023,se-palmeiras-sao-paulo,Sociedade Esportiva Palmeiras,BRA1,NaN,31,25.9,9,29.0,10,Nubank Parque,43713,+€31.54m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/se-palmeiras-s...
24,10492,esporte-clube-juventude,Esporte Clube Juventude,BRA1,NaN,29,28.3,3,10.3,0,Estádio Alfredo Jaconi,23726,+€1.13m,Roger Machado,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
43,10870,fortaleza-esporte-clube,Fortaleza Esporte Clube,BRA1,NaN,29,27.1,5,17.2,0,Estádio Governador Plácido Castelo,63904,+€6.25m,Juan Pablo Vojvoda,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/fortaleza-espo...
49,10997,clube-do-remo-pa-,Clube do Remo,BRA1,NaN,37,27.9,6,16.2,0,Estádio Evandro Almeida,13792,€-2.84m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/clube-do-remo-...
184,17776,chapecoense,Associação Chapecoense de Futebol,BRA1,NaN,34,28.0,2,5.9,0,Arena Condá,22600,+-0,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/chapecoense/st...
206,199,corinthians-sao-paulo,Sport Club Corinthians Paulista,BRA1,NaN,34,27.2,7,20.6,3,Neo Química Arena,49205,+€2.19m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/corinthians-sa...
211,2029,ceara-sporting-club,Ceará Sporting Club,BRA1,NaN,29,28.0,2,6.9,0,Estádio Governador Plácido Castelo,63904,+€2.30m,Anderson Batatais,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/ceara-sporting...
221,210,gremio-porto-alegre,Grêmio Foot-Ball Porto Alegrense,BRA1,NaN,34,26.5,11,32.4,3,Arena do Grêmio,60540,€-6.38m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/gremio-porto-a...
224,2125,esporte-clube-vitoria,Esporte Clube Vitória,BRA1,NaN,39,28.3,7,17.9,0,Estádio Manoel Barradas,30793,+€1.36m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
230,221,fc-santos,Santos Futebol Clube,BRA1,NaN,37,26.7,9,24.3,4,Estádio Urbano Caldeira,16068,+€7.21m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fc-santos/star...
286,2462,fluminense-rio-de-janeiro,Fluminense Football Club,BRA1,NaN,33,29.7,11,33.3,4,Estádio Jornalista Mário Filho,82238,€-6.76m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fluminense-rio...
389,330,clube-atletico-mineiro,Clube Atlético Mineiro,BRA1,NaN,33,25.7,9,27.3,6,Arena MRV,44892,€-1.24m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/clube-atletico...
456,3876,mirassol-futebol-clube-sp-,Mirasol Futebol Clube,BRA1,NaN,32,30.1,1,3.1,0,Estádio Municipal José María de Campos Maia,14534,+€1.67m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/mirassol-futeb...
569,537,botafogo-rio-de-janeiro,S. A. F. Botafogo,BRA1,NaN,34,26.2,13,38.2,5,Estádio Olímpico Nilton Santos,46931,+€40.04m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/botafogo-rio-d...
592,585,fc-sao-paulo,São Paulo Futebol Clube,BRA1,NaN,42,26.4,9,21.4,3,MorumBIS,72039,+€24.69m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fc-sao-paulo/s...
607,609,ec-cruzeiro-belo-horizonte,Cruzeiro Esporte Clube,BRA1,NaN,30,26.8,7,23.3,3,Estádio Governador Magalhães Pinto,61927,€-36.26m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/ec-cruzeiro-be...
614,614,flamengo-rio-de-janeiro,Clube de Regatas do Flamengo,BRA1,NaN,28,28.8,9,32.1,10,Estádio Jornalista Mário Filho,82238,€-13.92m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/flamengo-rio-d...
643,6600,sc-internacional-porto-alegre,Sport Club Internacional,BRA1,NaN,32,26.7,9,28.1,3,Estádio Beira-Rio,50848,+€41.39m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/sc-internacion...
657,679,club-athletico-paranaense,Clube Atlético Paranaense,BRA1,NaN,33,25.9,12,36.4,1,Estádio Mário Celso Petraglia,42372,€-1.51m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/club-athletico...
704,776,coritiba-fc,Coritiba Foot Ball Club,BRA1,NaN,32,28.3,4,12.5,0,Estádio Major Antônio Couto Pereira,40502,€-2.73m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/coritiba-fc/st...
745,8718,sport-club-do-recife,Sport Club do Recife,BRA1,NaN,29,27.1,1,3.4,0,Estádio Adelmar da Costa Carvalho,35000,+€2.95m,Mariano Soso,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/sport-club-do-...
749,8793,red-bull-bragantino,Red Bull Bragantino,BRA1,NaN,39,25.6,9,23.1,3,Estádio Municipal Cicero De Souza Marques,12000,+€10.50m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/red-bull-braga...
783,978,vasco-da-gama-rio-de-janeiro,Club de Regatas Vasco da Gama,BRA1,NaN,32,26.1,10,31.3,5,Estádio São Januário,24584,+€23.85m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/vasco-da-gama-...

In [6]:
df_clubs_brazil[['name', 'last_season']]

                                  name  last_season
2                  Esporte Clube Bahia         2025
11       Sociedade Esportiva Palmeiras         2025
24             Esporte Clube Juventude         2024
43             Fortaleza Esporte Clube         2024
49                       Clube do Remo         2025
184  Associação Chapecoense de Futebol         2025
206    Sport Club Corinthians Paulista         2025
211                Ceará Sporting Club         2024
221   Grêmio Foot-Ball Porto Alegrense         2025
224              Esporte Clube Vitória         2025
230               Santos Futebol Clube         2025
286           Fluminense Football Club         2025
389             Clube Atlético Mineiro         2025
456              Mirasol Futebol Clube         2025
569                  S. A. F. Botafogo         2025
592            São Paulo Futebol Clube         2025
607             Cruzeiro Esporte Clube         2025
614       Clube de Regatas do Flamengo         2025
643           Sport Club Internacional         2025
657          Clube Atlético Paranaense         2025
704            Coritiba Foot Ball Club         2025
745               Sport Club do Recife         2024
749                Red Bull Bragantino         2025
783      Club de Regatas Vasco da Gama         2025

In [7]:
df_clubs_brazil.sort_values('name')

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
184,17776,chapecoense,Associação Chapecoense de Futebol,BRA1,NaN,34,28.0,2,5.9,0,Arena Condá,22600,+-0,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/chapecoense/st...
211,2029,ceara-sporting-club,Ceará Sporting Club,BRA1,NaN,29,28.0,2,6.9,0,Estádio Governador Plácido Castelo,63904,+€2.30m,Anderson Batatais,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/ceara-sporting...
783,978,vasco-da-gama-rio-de-janeiro,Club de Regatas Vasco da Gama,BRA1,NaN,32,26.1,10,31.3,5,Estádio São Januário,24584,+€23.85m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/vasco-da-gama-...
389,330,clube-atletico-mineiro,Clube Atlético Mineiro,BRA1,NaN,33,25.7,9,27.3,6,Arena MRV,44892,€-1.24m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/clube-atletico...
657,679,club-athletico-paranaense,Clube Atlético Paranaense,BRA1,NaN,33,25.9,12,36.4,1,Estádio Mário Celso Petraglia,42372,€-1.51m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/club-athletico...
614,614,flamengo-rio-de-janeiro,Clube de Regatas do Flamengo,BRA1,NaN,28,28.8,9,32.1,10,Estádio Jornalista Mário Filho,82238,€-13.92m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/flamengo-rio-d...
49,10997,clube-do-remo-pa-,Clube do Remo,BRA1,NaN,37,27.9,6,16.2,0,Estádio Evandro Almeida,13792,€-2.84m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/clube-do-remo-...
704,776,coritiba-fc,Coritiba Foot Ball Club,BRA1,NaN,32,28.3,4,12.5,0,Estádio Major Antônio Couto Pereira,40502,€-2.73m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/coritiba-fc/st...
607,609,ec-cruzeiro-belo-horizonte,Cruzeiro Esporte Clube,BRA1,NaN,30,26.8,7,23.3,3,Estádio Governador Magalhães Pinto,61927,€-36.26m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/ec-cruzeiro-be...
2,10010,esporte-clube-bahia,Esporte Clube Bahia,BRA1,NaN,32,26.6,9,28.1,3,Arena Fonte Nova,47364,+€8.14m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
24,10492,esporte-clube-juventude,Esporte Clube Juventude,BRA1,NaN,29,28.3,3,10.3,0,Estádio Alfredo Jaconi,23726,+€1.13m,Roger Machado,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
224,2125,esporte-clube-vitoria,Esporte Clube Vitória,BRA1,NaN,39,28.3,7,17.9,0,Estádio Manoel Barradas,30793,+€1.36m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
286,2462,fluminense-rio-de-janeiro,Fluminense Football Club,BRA1,NaN,33,29.7,11,33.3,4,Estádio Jornalista Mário Filho,82238,€-6.76m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fluminense-rio...
43,10870,fortaleza-esporte-clube,Fortaleza Esporte Clube,BRA1,NaN,29,27.1,5,17.2,0,Estádio Governador Plácido Castelo,63904,+€6.25m,Juan Pablo Vojvoda,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/fortaleza-espo...
221,210,gremio-porto-alegre,Grêmio Foot-Ball Porto Alegrense,BRA1,NaN,34,26.5,11,32.4,3,Arena do Grêmio,60540,€-6.38m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/gremio-porto-a...
456,3876,mirassol-futebol-clube-sp-,Mirasol Futebol Clube,BRA1,NaN,32,30.1,1,3.1,0,Estádio Municipal José María de Campos Maia,14534,+€1.67m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/mirassol-futeb...
749,8793,red-bull-bragantino,Red Bull Bragantino,BRA1,NaN,39,25.6,9,23.1,3,Estádio Municipal Cicero De Souza Marques,12000,+€10.50m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/red-bull-braga...
569,537,botafogo-rio-de-janeiro,S. A. F. Botafogo,BRA1,NaN,34,26.2,13,38.2,5,Estádio Olímpico Nilton Santos,46931,+€40.04m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/botafogo-rio-d...
230,221,fc-santos,Santos Futebol Clube,BRA1,NaN,37,26.7,9,24.3,4,Estádio Urbano Caldeira,16068,+€7.21m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fc-santos/star...
11,1023,se-palmeiras-sao-paulo,Sociedade Esportiva Palmeiras,BRA1,NaN,31,25.9,9,29.0,10,Nubank Parque,43713,+€31.54m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/se-palmeiras-s...
206,199,corinthians-sao-paulo,Sport Club Corinthians Paulista,BRA1,NaN,34,27.2,7,20.6,3,Neo Química Arena,49205,+€2.19m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/corinthians-sa...
643,6600,sc-internacional-porto-alegre,Sport Club Internacional,BRA1,NaN,32,26.7,9,28.1,3,Estádio Beira-Rio,50848,+€41.39m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/sc-internacion...
745,8718,sport-club-do-recife,Sport Club do Recife,BRA1,NaN,29,27.1,1,3.4,0,Estádio Adelmar da Costa Carvalho,35000,+€2.95m,Mariano Soso,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/sport-club-do-...
592,585,fc-sao-paulo,São Paulo Futebol Clube,BRA1,NaN,42,26.4,9,21.4,3,MorumBIS,72039,+€24.69m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fc-sao-paulo/s...

In [8]:
df_clubs_brazil_current = df_clubs_brazil[df_clubs_brazil['last_season'] == 2025]
df_clubs_brazil_current

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
2,10010,esporte-clube-bahia,Esporte Clube Bahia,BRA1,NaN,32,26.6,9,28.1,3,Arena Fonte Nova,47364,+€8.14m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
11,1023,se-palmeiras-sao-paulo,Sociedade Esportiva Palmeiras,BRA1,NaN,31,25.9,9,29.0,10,Nubank Parque,43713,+€31.54m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/se-palmeiras-s...
49,10997,clube-do-remo-pa-,Clube do Remo,BRA1,NaN,37,27.9,6,16.2,0,Estádio Evandro Almeida,13792,€-2.84m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/clube-do-remo-...
184,17776,chapecoense,Associação Chapecoense de Futebol,BRA1,NaN,34,28.0,2,5.9,0,Arena Condá,22600,+-0,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/chapecoense/st...
206,199,corinthians-sao-paulo,Sport Club Corinthians Paulista,BRA1,NaN,34,27.2,7,20.6,3,Neo Química Arena,49205,+€2.19m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/corinthians-sa...
221,210,gremio-porto-alegre,Grêmio Foot-Ball Porto Alegrense,BRA1,NaN,34,26.5,11,32.4,3,Arena do Grêmio,60540,€-6.38m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/gremio-porto-a...
224,2125,esporte-clube-vitoria,Esporte Clube Vitória,BRA1,NaN,39,28.3,7,17.9,0,Estádio Manoel Barradas,30793,+€1.36m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
230,221,fc-santos,Santos Futebol Clube,BRA1,NaN,37,26.7,9,24.3,4,Estádio Urbano Caldeira,16068,+€7.21m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fc-santos/star...
286,2462,fluminense-rio-de-janeiro,Fluminense Football Club,BRA1,NaN,33,29.7,11,33.3,4,Estádio Jornalista Mário Filho,82238,€-6.76m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fluminense-rio...
389,330,clube-atletico-mineiro,Clube Atlético Mineiro,BRA1,NaN,33,25.7,9,27.3,6,Arena MRV,44892,€-1.24m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/clube-atletico...
456,3876,mirassol-futebol-clube-sp-,Mirasol Futebol Clube,BRA1,NaN,32,30.1,1,3.1,0,Estádio Municipal José María de Campos Maia,14534,+€1.67m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/mirassol-futeb...
569,537,botafogo-rio-de-janeiro,S. A. F. Botafogo,BRA1,NaN,34,26.2,13,38.2,5,Estádio Olímpico Nilton Santos,46931,+€40.04m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/botafogo-rio-d...
592,585,fc-sao-paulo,São Paulo Futebol Clube,BRA1,NaN,42,26.4,9,21.4,3,MorumBIS,72039,+€24.69m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fc-sao-paulo/s...
607,609,ec-cruzeiro-belo-horizonte,Cruzeiro Esporte Clube,BRA1,NaN,30,26.8,7,23.3,3,Estádio Governador Magalhães Pinto,61927,€-36.26m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/ec-cruzeiro-be...
614,614,flamengo-rio-de-janeiro,Clube de Regatas do Flamengo,BRA1,NaN,28,28.8,9,32.1,10,Estádio Jornalista Mário Filho,82238,€-13.92m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/flamengo-rio-d...
643,6600,sc-internacional-porto-alegre,Sport Club Internacional,BRA1,NaN,32,26.7,9,28.1,3,Estádio Beira-Rio,50848,+€41.39m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/sc-internacion...
657,679,club-athletico-paranaense,Clube Atlético Paranaense,BRA1,NaN,33,25.9,12,36.4,1,Estádio Mário Celso Petraglia,42372,€-1.51m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/club-athletico...
704,776,coritiba-fc,Coritiba Foot Ball Club,BRA1,NaN,32,28.3,4,12.5,0,Estádio Major Antônio Couto Pereira,40502,€-2.73m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/coritiba-fc/st...
749,8793,red-bull-bragantino,Red Bull Bragantino,BRA1,NaN,39,25.6,9,23.1,3,Estádio Municipal Cicero De Souza Marques,12000,+€10.50m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/red-bull-braga...
783,978,vasco-da-gama-rio-de-janeiro,Club de Regatas Vasco da Gama,BRA1,NaN,32,26.1,10,31.3,5,Estádio São Januário,24584,+€23.85m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/vasco-da-gama-...

## Loading players data

In [9]:
df_players = pd.read_csv('../data/raw/players.csv')

## Exploring players structure

In [10]:
df_players.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus FC,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,IFM,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,Bayern Munich,100000.0,3000000.0

In [11]:
df_players.columns

Index(['player_id', 'first_name', 'last_name', 'name', 'last_season',
       'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth',
       'country_of_citizenship', 'date_of_birth', 'sub_position', 'position',
       'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name',
       'image_url', 'international_caps', 'international_goals',
       'current_national_team_id', 'url',
       'current_club_domestic_competition_id', 'current_club_name',
       'market_value_in_eur', 'highest_market_value_in_eur'],
      dtype='str')

In [12]:
df_players.info()

<class 'pandas.DataFrame'>
RangeIndex: 50149 entries, 0 to 50148
Data columns (total 26 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   player_id                             50149 non-null  int64
 1   first_name                            46988 non-null  str
 2   last_name                             50149 non-null  str
 3   name                                  50149 non-null  str
 4   last_season                           50149 non-null  int64
 5   current_club_id                       50149 non-null  int64
 6   player_code                           50149 non-null  str
 7   country_of_birth                      44264 non-null  str
 8   city_of_birth                         44541 non-null  str
 9   country_of_citizenship                49880 non-null  str
 10  date_of_birth                         50100 non-null  str
 11  sub_position                          49563 non-null  str
 12  position                              50149 non-null  str
 13  foot                                  44256 non-null  str
 14  height_in_cm                          45784 non-null  float64
 15  contract_expiration_date              31580 non-null  str
 16  agent_name                            26854 non-null  str
 17  image_url                             50149 non-null  str
 18  international_caps                    19356 non-null  float64
 19  international_goals                   19356 non-null  float64
 20  current_national_team_id              3260 non-null   float64
 21  url                                   50149 non-null  str
 22  current_club_domestic_competition_id  47163 non-null  str
 23  current_club_name                     47163 non-null  str
 24  market_value_in_eur                   41528 non-null  float64
 25  highest_market_value_in_eur           41528 non-null  float64
dtypes: float64(6), int64(3), str(17)
memory usage: 9.9 MB

In [13]:
df_players['last_season'].value_counts()

last_season
2025    22292
2024     6075
2023     2092
2018     2065
2013     2061
2022     1877
2020     1843
2016     1831
2021     1817
2017     1661
2014     1660
2012     1658
2015     1651
2019     1566
Name: count, dtype: int64

## Merging players with Brazilian clubs

In [14]:
df_players_brazil = pd.merge(df_players, df_clubs_brazil_current, left_on='current_club_id', right_on='club_id')
df_players_brazil

,player_id,first_name,last_name,name_x,last_season_x,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season_y,filename,url_y
0,10471,NaN,Luiz Gustavo,Luiz Gustavo,2025,679,luiz-gustavo,Brazil,Pindamonhangaba,Brazil,...,12,36.4,1,Estádio Mário Celso Petraglia,42372,€-1.51m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/club-athletico...
1,22415,NaN,Fábio,Fábio,2025,2462,fabio,Brazil,Nobres,Brazil,...,11,33.3,4,Estádio Jornalista Mário Filho,82238,€-6.76m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fluminense-rio...
2,29241,Thiago,Silva,Thiago Silva,2025,2462,thiago-silva,Brazil,Rio de Janeiro,Brazil,...,11,33.3,4,Estádio Jornalista Mário Filho,82238,€-6.76m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fluminense-rio...
3,37647,Dimitri,Payet,Dimitri Payet,2024,978,dimitri-payet,Réunion,Saint-Pierre,France,...,10,31.3,5,Estádio São Januário,24584,+€23.85m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/vasco-da-gama-...
4,45319,Gabriel,Mercado,Gabriel Mercado,2025,6600,gabriel-mercado,Argentina,Puerto Madryn,Argentina,...,9,28.1,3,Estádio Beira-Rio,50848,+€41.39m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/sc-internacion...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,1471677,NaN,Alisson,Alisson,2024,6600,alisson,Brazil,Porto Alegre,Brazil,...,9,28.1,3,Estádio Beira-Rio,50848,+€41.39m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/sc-internacion...
1040,1488557,NaN,Gabriel Werneck,Gabriel Werneck,2024,614,gabriel-werneck,Brazil,Juiz de Fora,Brazil,...,9,32.1,10,Estádio Jornalista Mário Filho,82238,€-13.92m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/flamengo-rio-d...
1041,1488788,NaN,Gui Amorim,Gui Amorim,2024,199,gui-amorim,NaN,NaN,Brazil,...,7,20.6,3,Neo Química Arena,49205,+€2.19m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/corinthians-sa...
1042,1500420,NaN,Bruninho,Bruninho,2025,679,bruninho,Brazil,São Paulo,Brazil,...,12,36.4,1,Estádio Mário Celso Petraglia,42372,€-1.51m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/club-athletico...
1043,1519143,NaN,Anderson Pato,Anderson Pato,2025,2125,anderson-pato,Brazil,Salvador,Brazil,...,7,17.9,0,Estádio Manoel Barradas,30793,+€1.36m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...

In [15]:
df_players_brazil['player_id'].duplicated().sum()

np.int64(0)

In [16]:
df_players_brazil.groupby('current_club_name').size()

current_club_name
Associação Chapecoense de Futebol    38
Club de Regatas Vasco da Gama        63
Clube Atlético Mineiro               62
Clube Atlético Paranaense            34
Clube de Regatas do Flamengo         59
Clube do Remo                        40
Coritiba Foot Ball Club              33
Cruzeiro Esporte Clube               44
Esporte Clube Bahia                  64
Esporte Clube Vitória                80
Fluminense Football Club             65
Grêmio Foot-Ball Porto Alegrense     50
Mirasol Futebol Clube                60
Red Bull Bragantino                  52
S. A. F. Botafogo                    69
Santos Futebol Clube                 49
Sociedade Esportiva Palmeiras        40
Sport Club Corinthians Paulista      43
Sport Club Internacional             48
São Paulo Futebol Clube              51
dtype: int64

In [17]:
df_players_brazil['last_season_x'].value_counts()

last_season_x
2025    706
2024    338
Name: count, dtype: int64

In [18]:
df_players_brazil_active = df_players_brazil[df_players_brazil['last_season_x'] == 2025]
df_players_brazil_active

,player_id,first_name,last_name,name_x,last_season_x,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season_y,filename,url_y
0,10471,NaN,Luiz Gustavo,Luiz Gustavo,2025,679,luiz-gustavo,Brazil,Pindamonhangaba,Brazil,...,12,36.4,1,Estádio Mário Celso Petraglia,42372,€-1.51m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/club-athletico...
1,22415,NaN,Fábio,Fábio,2025,2462,fabio,Brazil,Nobres,Brazil,...,11,33.3,4,Estádio Jornalista Mário Filho,82238,€-6.76m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fluminense-rio...
2,29241,Thiago,Silva,Thiago Silva,2025,2462,thiago-silva,Brazil,Rio de Janeiro,Brazil,...,11,33.3,4,Estádio Jornalista Mário Filho,82238,€-6.76m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fluminense-rio...
4,45319,Gabriel,Mercado,Gabriel Mercado,2025,6600,gabriel-mercado,Argentina,Puerto Madryn,Argentina,...,9,28.1,3,Estádio Beira-Rio,50848,+€41.39m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/sc-internacion...
5,47592,NaN,Fagner,Fagner,2025,609,fagner,Brazil,São Paulo,Brazil,...,7,23.3,3,Estádio Governador Magalhães Pinto,61927,€-36.26m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/ec-cruzeiro-be...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1029,1410674,Mamady,Cissé,Mamady Cissé,2025,330,mamady-cisse,Guinea,Conakry,Guinea,...,9,27.3,6,Arena MRV,44892,€-1.24m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/clube-atletico...
1037,1446971,NaN,Gabriel Menegon,Gabriel Menegon,2025,210,gabriel-menegon,Brazil,Sapiranga,Brazil,...,11,32.4,3,Arena do Grêmio,60540,€-6.38m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/gremio-porto-a...
1038,1464878,Kadir,Barría,Kadir Barría,2025,537,kadir-barria,Panama,Ciudad de Panamá,Panama,...,13,38.2,5,Estádio Olímpico Nilton Santos,46931,+€40.04m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/botafogo-rio-d...
1042,1500420,NaN,Bruninho,Bruninho,2025,679,bruninho,Brazil,São Paulo,Brazil,...,12,36.4,1,Estádio Mário Celso Petraglia,42372,€-1.51m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/club-athletico...
1043,1519143,NaN,Anderson Pato,Anderson Pato,2025,2125,anderson-pato,Brazil,Salvador,Brazil,...,7,17.9,0,Estádio Manoel Barradas,30793,+€1.36m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...

## Conclusion

- Loaded clubs.csv and players.csv
- Filtered clubs to Brazilian Série A, current season (20 clubs)
- Merged players with current Brazilian clubs via current_club_id
- Filtered to active players (last_season == 2025): [X] players
- Result stored in df_players_brazil_active, ready for market value analysis